# Generated by Django 4.1.1 on 2022-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_planos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planos',
            name='descricao',
            field=models.TextField(max_length=100, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='planos',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
    ]
